#!/usr/bin/env python3
"""
Compare token sequences generated by PyTorch parler-tts vs our MLX implementation.
Uses greedy decoding (temperature=0) for determinism.

Run from repo root:
    python scripts/compare_tokens.py
"""

import sys
import numpy as np
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

REPO_ID = "ai4bharat/indic-parler-tts"
DESC    = "A female speaker delivers clear speech at a moderate pace."
TEXT    = "Hello, how are you?"
MAX_S   = 3.0  # short to keep runtime low

# ══════════════════════════════════════════════════════════════════════════════
# 1. PYTORCH — greedy decode, dump token sequence
# ══════════════════════════════════════════════════════════════════════════════
print("=" * 60)
print("PYTORCH greedy tokens")
print("=" * 60)

import torch
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer

model_pt = ParlerTTSForConditionalGeneration.from_pretrained(REPO_ID).eval()
prompt_tok = AutoTokenizer.from_pretrained(REPO_ID)
desc_tok   = AutoTokenizer.from_pretrained(model_pt.config.text_encoder._name_or_path)

desc_enc   = desc_tok(DESC, return_tensors="pt")
prompt_enc = prompt_tok(TEXT, return_tensors="pt")

# hook: intercept logits at each decoder step
pt_logits_per_step = []

orig_forward = model_pt.decoder.model.forward
def hooked_forward(*args, **kwargs):
    out = orig_forward(*args, **kwargs)
    return out

# Patch generate to capture output_ids before DAC decode.
# We monkeypatch at the ParlerTTS model level to intercept after delay-pattern revert.
pt_codes_captured = []

import types
import parler_tts.modeling_parler_tts as _pt_mod
_orig_pt_generate = model_pt.__class__.generate

def _patched_pt_generate(self, *args, **kwargs):
    # Hook: patch audio_encoder.decode (bound method) to capture codes before DAC
    _real_decode = self.audio_encoder.decode

    class _FakeDecodeOutput:
        audio_values = torch.zeros(1, 1, 4096)

    def _capture_decode(audio_codes, audio_scales=None, **kw):
        pt_codes_captured.append(audio_codes.squeeze(0).cpu().numpy())
        return _FakeDecodeOutput()

    # Use __dict__ to bypass nn.Module's setattr on the instance
    self.audio_encoder.__dict__['decode'] = _capture_decode
    try:
        result = _orig_pt_generate(self, *args, **kwargs)
    finally:
        self.audio_encoder.__dict__.pop('decode', None)
    return result

model_pt.generate = types.MethodType(_patched_pt_generate, model_pt)

# run greedy (do_sample=False)
with torch.no_grad():
    max_new = int(MAX_S * 44100 / 512) + 9 + 5  # frames + drain + slack
    _ = model_pt.generate(
        input_ids=desc_enc.input_ids,
        attention_mask=desc_enc.attention_mask,
        prompt_input_ids=prompt_enc.input_ids,
        prompt_attention_mask=prompt_enc.attention_mask,
        do_sample=False,
        max_new_tokens=max_new,
    )

NUM_CB = model_pt.decoder.num_codebooks
BOS = model_pt.generation_config.bos_token_id
PAD = model_pt.generation_config.pad_token_id
EOS = model_pt.generation_config.eos_token_id

pt_codes = pt_codes_captured[0]  # (9, T)
print(f"[PT] audio codes shape: {pt_codes.shape}")
print(f"[PT] first 10 frames per codebook:")
for k in range(NUM_CB):
    print(f"  CB{k}: {pt_codes[k, :10].tolist()}")

# ══════════════════════════════════════════════════════════════════════════════
# 2. MLX — greedy decode (temperature=0)
# ══════════════════════════════════════════════════════════════════════════════
print()
print("=" * 60)
print("MLX greedy tokens")
print("=" * 60)

import mlx.core as mx
from models.indic_parler_tts import load_model, generate

model_mlx, tokenizers = load_model(REPO_ID, strict_load=True, audit_load=True)

# Monkey-patch generate to use temperature=0, capture tokens
desc_ids_np   = desc_tok(DESC, return_tensors="np").input_ids
prompt_ids_np = prompt_tok(TEXT, return_tensors="np").input_ids
desc_mx   = mx.array(desc_ids_np, dtype=mx.int32)
prompt_mx = mx.array(prompt_ids_np, dtype=mx.int32)

# Run with temperature=0 (greedy) and capture the generated codes
# We'll patch model.generate to dump codes before DAC
original_dac_decode = model_mlx.dac.decode

mlx_codes_captured = []

# Patch at the generate level to capture codes array before DAC
import models.indic_parler_tts.model as _mlx_model_mod
_orig_generate = model_mlx.generate.__func__

def _patched_generate(self, desc_ids, prompt_ids, **kw):
    # wrap dac.decode to intercept codes
    _orig_dac = self.dac.decode
    def _capture(codes_mx):
        mlx_codes_captured.append(np.array(codes_mx))
        return _orig_dac(codes_mx)
    self.dac.decode = _capture
    result = _orig_generate(self, desc_ids, prompt_ids, **kw)
    self.dac.decode = _orig_dac
    return result

import types
model_mlx.generate = types.MethodType(_patched_generate, model_mlx)

_ = model_mlx.generate(
    desc_mx, prompt_mx,
    max_audio_length_s=MAX_S,
    temperature=0.0,  # greedy
    top_k=0,
    top_p=1.0,
    seed=0,
)

if mlx_codes_captured:
    mlx_codes = mlx_codes_captured[0]  # (9, T)
    print(f"[MLX] audio codes shape: {mlx_codes.shape}")
    print(f"[MLX] first 10 frames per codebook:")
    for k in range(NUM_CB):
        print(f"  CB{k}: {mlx_codes[k, :10].tolist()}")
else:
    print("[MLX] No codes captured — generation may have returned empty")
    mlx_codes = None

# ══════════════════════════════════════════════════════════════════════════════
# 3. COMPARE
# ══════════════════════════════════════════════════════════════════════════════
print()
print("=" * 60)
print("COMPARISON")
print("=" * 60)

if mlx_codes is None:
    print("MLX returned no codes — cannot compare.")
    sys.exit(1)

T_min = min(pt_codes.shape[1], mlx_codes.shape[1])
print(f"Comparing first {T_min} frames")

for k in range(NUM_CB):
    pt_k  = pt_codes[k, :T_min]
    mlx_k = mlx_codes[k, :T_min]
    matches = (pt_k == mlx_k)
    first_diff = int(np.argmin(matches)) if not matches.all() else T_min
    pct_match = matches.mean() * 100
    print(f"CB{k}: {pct_match:.1f}% match, first divergence at frame {first_diff}  "
          f"(PT={pt_k[first_diff] if first_diff < T_min else 'same'}, "
          f"MLX={mlx_k[first_diff] if first_diff < T_min else 'same'})")

print()
overall = (pt_codes[:, :T_min] == mlx_codes[:, :T_min]).mean()
print(f"Overall token match: {overall*100:.1f}%")
